# Generated by Django 5.1.3 on 2024-12-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socializing', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(default='videos/ea.mp3', upload_to='videos/'),
        ),
    ]
